# Generated by Django 4.2.7 on 2025-09-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivery_instructions',
        ),
        migrations.RemoveField(
            model_name='package',
            name='service_area',
        ),
        migrations.AddField(
            model_name='package',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='distance_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='declared_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('document', 'Document'), ('package', 'Package'), ('fragile', 'Fragile'), ('perishable', 'Perishable')], db_index=True, default='package', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_zip',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender_city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender_phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender_state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender_zip',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='area_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status', 'created_at'], name='package_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tracking_number'], name='package_tracking_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['sender', 'status'], name='package_sender_status_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['created_at'], name='package_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['recipient_name'], name='package_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['area_name'], name='servicearea_name_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['active'], name='servicearea_active_idx'),
        ),
    ]
